[package]
name = "portdog"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.46", features = ["derive"]}
netstat2 = "0.11.2"
sysinfo = "0.37.0"
[target.'cfg(unix)'.dependencies]
nix = { version = "0.30.1", default-features = false, features = ["signal"] }
